name: dev

services:
  nginx:
    container_name: dev-nginx
    build:
      context: docker/development
      dockerfile: nginx/Dockerfile
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./src:/app

  php-fpm:
    container_name: dev-php-fpm
    build:
      context: docker/development
      dockerfile: php-fpm/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-8.3}"
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
        INSTALL_XDEBUG: "${INSTALL_XDEBUG:-false}"
        XDEBUG_VERSION: "${XDEBUG_VERSION:-3.2.2}"
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVER_NAME:-app-loc}"
    volumes:
      - ./src:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    container_name: dev-php-cli
    build:
      context: docker/development
      dockerfile: php-cli/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-8.3}"
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
        INSTALL_XDEBUG: "${INSTALL_XDEBUG:-false}"
        XDEBUG_VERSION: "${XDEBUG_VERSION:-3.2.2}"
    volumes:
      - ./src:/app
      - ./docker/development/php-cli/bash/.bashrc:/home/www-data/.bashrc
      - ./docker/development/php-cli/bash/.bash_history:/home/www-data/.bash_history
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    container_name: dev-node
    build:
      context: docker/development
      dockerfile: node/Dockerfile
      args:
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
    ports:
      - "${FORWARD_VITE_PORT:-5173}:5173"
    environment:
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - ./src:/app
      - ./docker/development/node/bash/.bashrc:/home/node/.bashrc
      - ./docker/development/node/bash/.bash_history:/home/node/.bash_history

  mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.6}"
    container_name: dev-mariadb
    profiles:
      - mariadb
    ports:
      - "${FORWARD_MARIADB_PORT:-3306}:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-root}"
      MARIADB_DATABASE: "${MARIADB_DATABASE:-app}"
      MARIADB_USER: "${MARIADB_USERNAME:-app}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD:-secret}"
    volumes:
      - mariadb_data:/var/lib/mysql

  postgres:
    image: "postgres:${POSTGRES_VERSION:-17-alpine}"
    container_name: dev-postgres
    profiles:
      - postgres
    ports:
      - "${FORWARD_PG_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${PG_DATABASE:-app}"
      POSTGRES_USER: "${PG_USERNAME:-app}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-secret}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:${REDIS_VERSION:-7-alpine}"
    container_name: dev-redis
    profiles:
      - redis
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  buggregator:
    image: "ghcr.io/buggregator/server:latest"
    container_name: dev-buggregator
    profiles:
      - buggregator
    ports:
      - "8000:8000"
      - "1025:1025"
      - "9912:9912"
      - "9913:9913"

volumes:
  mariadb_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
