name: "dev-app"

services:
  nginx:
    container_name: "dev-app-nginx"
    build:
      context: "docker/development"
      dockerfile: "nginx/Dockerfile"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
    ports:
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - "./src:/app"

  php-fpm:
    container_name: "dev-app-php-fpm"
    build:
      context: "docker/development"
      dockerfile: "php-fpm/Dockerfile"
      args:
        PHP_VERSION: "${PHP_VERSION:-8.3}"
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
        INSTALL_XDEBUG: "${INSTALL_XDEBUG:-false}"
        XDEBUG_VERSION: "${XDEBUG_VERSION:-3.2.2}"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVER_NAME:-dev-app}"
    volumes:
      - "./src:/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    container_name: "dev-app-php-cli"
    build:
      context: "docker/development"
      dockerfile: "php-cli/Dockerfile"
      args:
        PHP_VERSION: "${PHP_VERSION:-8.3}"
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
        INSTALL_XDEBUG: "${INSTALL_XDEBUG:-false}"
        XDEBUG_VERSION: "${XDEBUG_VERSION:-3.2.2}"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
    volumes:
      - ./src:/app
      - ./docker/development/php-cli/bash/.bashrc:/home/www-data/.bashrc
      - ./docker/development/php-cli/bash/.bash_history:/home/www-data/.bash_history
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    container_name: "dev-app-node"
    build:
      context: "docker/development"
      dockerfile: "node/Dockerfile"
      args:
        HOST_USER_ID: "${HOST_USER_ID:-1000}"
        HOST_GROUP_ID: "${HOST_GROUP_ID:-1000}"
    ports:
      - "${FORWARD_VITE_PORT:-5173}:5173"
    environment:
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - "./src:/app"
      - "./docker/development/node/bash:/home/node"

  mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.6}"
    container_name: "app-mariadb"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      TZ: "${TIMEZONE:-Europe/Berlin}"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MARIADB_DATABASE: "${DB_DATABASE:-app}"
      MARIADB_USER: "${DB_USERNAME:-app}"
      MARIADB_PASSWORD: "${DB_PASSWORD:-app}"
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    networks:
      - "default"

volumes:
  mariadb_data:
    driver: local